### ISSUE TITLE
Unable to install ngrok

### ISSUE THREAD

**Issue by DhruvMevada** [peakwinter/python-ngrok#3]
I tried with pip install ngrok but gets error:
C:\Users\dhruv.mevada>pip install ngrok
Collecting ngrok
  Could not find a version that satisfies the requirement ngrok (from versions:
)
No matching distribution found for ngrok

**Comment by peakwinter** [comment]
`pip install python-ngrok`

**Comment by DhruvMevada** [comment]
Thank you @peakwinter
